---
dist: xenial
sudo: required

language: python
python:
  - "2.7"
  - "3.7"
  - "3.4"

install:
  - pip install --upgrade pycodestyle

addons:
  sonarcloud:
    organization: "lean-delivery"

script:
  - pycodestyle
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sonar-scanner; fi'
