---
- hosts: localhost
  gather_facts: False
  vars:
    repo_url: "{{ lookup('env','repo_url') | default('https://github.com/lean-delivery/ansible-modules-aem.git', true)}}"
    modules_path: "{{ lookup('env','ansible_modules_path') | default('~/.ansible/plugins/modules', true)}}"
    modules_version: "{{ lookup('env','ansible_modules_version') | default('master', true)}}"
  tasks:
    - name: Make sure that modules directory is exists
      file:
        path: "{{ modules_path }}"
        state: directory
        mode: 0755
    - name: Install Ansible AEM Modules
      git:
        repo: "{{ repo_url }}"
        dest: "{{ modules_path }}/ansible-modules-aem"
        version: "{{ modules_version }}"
        force: yes
