---
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
name: CI
jobs:
  pycodestyle:
    name: PyCodeStyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: PyCodeStyle Scan
        uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "*.py"
          use-pylint: false
          use-pycodestyle: true
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pycodestyle-options: "--config=tox.ini --verbose"
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
